import {useState, useRef} from 'react'
import Head from 'next/head';
import Link from 'next/link';
import Modal from "./Modal"
import { useCart } from "../context/CartContext"
import { BsHandbag } from "react-icons/bs";
import { AiOutlineHeart, AiOutlineMenu, AiOutlineUser } from "react-icons/ai";
import Register from './Register';
import Login from './Login';
import { 
  Tabs,
  TabList,
  Tab,
  TabPanels,
  TabPanel,  
  ModalOverlay, 
  Button, 
  Drawer, 
  DrawerBody, 
  DrawerContent, 
  useDisclosure,
  // Link
   } from '@chakra-ui/react';
import { useBag } from '../context/BagContext';
import { useRouter } from 'next/router'
import { useSession } from 'next-auth/react';

const OverlayOne = () => (
  <ModalOverlay
    bg='blackAlpha.300'
    backdropFilter='blur(10px) hue-rotate(90deg)'
  />
)
const Navbar = () => {
  const router = useRouter()
  const [popUp, setPopUp] = useState(false)
  const [overlay, setOverlay] = useState(<OverlayOne />)
  const { isOpen, onOpen, onClose } = useDisclosure()
  const btnRef = useRef()
  const { items} = useCart()
  const { bag } = useBag()
  const session = useSession()

  const totalWishlist = items.length
  const totalbagItem = bag.length
   const modalHandler = () => {
    setPopUp(true)
    setOverlay(<OverlayOne />)
  }

  const checkoutBag = () => {
    if(session.status !== 'authenticated'){
     return setPopUp(true)
    }else {
      router.push('/checkout/bag')
    }
  }


  return (
    <>
    <Head>
      <title>Sneakfit</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico" />
    </Head>
      <nav className="bg-white px-1 border-b border-black fixed top-0 w-full z-50">
        <div className="flex justify-between items-center md:basis-full w-full">
          <Link href={"/"}>
              <a><img src="/sneaker_logo_2.svg" alt="Sneakfit Logo" className='w-24 cursor-pointer'/></a>
          </Link>
          <div className="hidden md:hidden md:w-auto lg:block"  id="navbar-default">
            {/* FIXME: one of link component or anchor tag is affecting server side routing during stripe checkout routing  */}
            <ul className={ "active flex flex-col p-4 mt-4 uppercase bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium font-black xl:text-lg md:bg-white"}>
              <li>
                <Link href='/men/sneakers' >
                  <a className={(router.asPath == '/men/sneakers' ? 'active' : '') + " nav-link block font-bold py-2 pr-4 pl-3 text-base text-white rounded md:bg-transparent md:text-black md:p-0"}>Men</a>
                </Link>
              </li>
              <li>
                <Link href={'/women/sneakers'}>
                  <a className={(router.asPath == '/women/sneakers' ? "active": "") + " nav-link block font-bold py-2 pr-4 pl-3 text-base text-white rounded md:bg-transparent md:text-black md:p-0"}>Women</a>
                </Link>
              </li>
              <li>
                <Link href={'/kids/sneakers'}>
                  <a className={(router.asPath == '/kids/sneakers' ? 'active' : '') + " nav-link block font-bold py-2 pr-4 pl-3 text-base text-white rounded md:bg-transparent md:text-black md:p-0"}>Kids</a>
                </Link>
              </li>
              <li>
                <Link href={'#'}>
                  <a className="nav-link block py-2 pr-4 pl-3 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 text-black text-base font-bold md:p-0">New Arrivals</a>
                </Link>
              </li>
              <li>
                <Link href={'#'}>
                  <a className=" nav-link block py-2 pr-4 pl-3 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 text-black text-base font-bold md:p-0">culture</a>
                </Link>
              </li>
              <li>
                <Link href={'#'}>
                  <a className="nav-link block py-2 pr-4 pl-3 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 text-black text-base font-bold md:p-0">brands</a>
                </Link>
              </li>
            </ul>
          </div>
         
          <div className='flex flex-1 flex-row-reverse gap-x-3 lg:flex-row lg:gap-x-0 lg:flex-none'>
            <button onClick={modalHandler} type="button" className="relative font-bold p-1 lg:mr-5 text-2xl rounded-lg focus:outline-none  lg:block focus:ring-2 focus:ring-transparent">
              <AiOutlineUser fontSize={16} />
            </button>
           
            <Link href='/wishlist'>
              <a type="button" className="hidden lg:block relative p-1 rounded-lg lg:mr-5 mr-2 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-transparent">
                <AiOutlineHeart fontSize={16}/>
                <div className="inline-flex absolute -bottom-2 -right-2 justify-center items-center w-6 h-6 text-xs font-bold text-black">{totalWishlist}</div>
              </a>
            </Link>

              <button onClick={checkoutBag} type="button" className=" relative p-1 rounded-lg lg:mr-2 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-transparent" >
                <BsHandbag fontSize={16} fontWeight={'400'} className='font-bold'/>
                <div className="inline-flex absolute -bottom-2 -right-2 justify-center items-center w-6 h-6 text-xs font-bold text-black">{totalbagItem}</div>
              </button >
          
          </div>

          <div className='lg:hidden xl:hidden border-l border-black'>
            <Button ref={btnRef} colorScheme='transparent' p={'6'} onClick={onOpen}>
              <AiOutlineMenu size={20} className='text-black'/>
            </Button>
            <Drawer
              isOpen={isOpen}
              placement='right'
              onClose={onClose}
              finalFocusRef={btnRef}
              size={'full'}
            >
            
              <DrawerContent height={'100%'} marginTop={'50px'}>

                <DrawerBody className='flex flex-col gap-y-9'>
                 <Link href={'/'}><a className='uppercase font-bold text-5xl'>home</a></Link>
                 <Link href={'/men/sneakers'}><a className='uppercase font-bold text-5xl'>men </a></Link>
                 <Link href={'/women/sneakers'}><a className='uppercase font-bold text-5xl'>women </a></Link>
                 <Link href={'/kids/sneakers'}><a className='uppercase font-bold text-5xl'>kids</a></Link>
                 <Link href={'#'}><a className='uppercase font-bold text-5xl'>new arrival</a></Link>
                 <Link href={'#'}><a className='uppercase font-bold text-5xl'>culture</a></Link>
                 <Link href='/wishlist'><a className='uppercase font-bold text-5xl'>wishlist({totalWishlist})</a></Link>
                </DrawerBody>

              </DrawerContent>
            </Drawer>
          </div>
        </div>
      </nav>
      

      {/* user sign up and login modal */}
      <Modal onOpen={popUp} setPopUp={setPopUp} overlay={overlay}>
        <Tabs >
          <TabList>
            <Tab className='uppercase text-lg'>sign in</Tab>
            <Tab className='uppercase text-lg'>i&apos;m new here</Tab>
          </TabList>

          <TabPanels>
            <TabPanel>
              <Login/>
            </TabPanel>
            <TabPanel>
              <Register/>
            </TabPanel>
          </TabPanels>
        </Tabs>
      </Modal>
    </>
  )
}

export default Navbar