import React from 'react'
import Image from "next/image";
import Head from 'next/head'
import { BsHandbag, BsSearch, BsSuitHeart } from "react-icons/bs";
import { BiMenu } from "react-icons/bi";

const Navbar = () => {
  return (
    <>
    <Head>
      <title>Sneakfit</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <nav className="bg-white border-gray-200 px-2 sm:px-4 py-2.5">
      <div className="container flex flex-wrap justify-between items-center mx-auto">
        <div>
          <button type="button" className="p-1 mr-5 text-2xl rounded-lg md:hidden focus:outline-none focus:ring-2">
            <BiMenu />
          </button>
          <button type="button" className="p-1 text-xl rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200">
            <BsSearch/>
          </button>         
        </div>
        {/* <a href="https://flowbite.com/" className="flex items-center"> */}
            <Image src="/SNEAKFIT.svg" width={100} height={32} alt="Sneakfit Logo" />
        {/* </a> */}
        <div>
          <button type="button" className="p-1 text-xl mr-5 rounded-lg md:hidden focus:outline-none focus:ring-2">
            <BsSuitHeart />
          </button>
          <button type="button" className="p-1 text-xl rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" >
            <BsHandbag/>
          </button>
        </div>
        <div className="hidden w-full md:block md:w-auto" id="navbar-default">
          <ul className="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
            <li>
              <a href="#" className="block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" aria-current="page">Home</a>
            </li>
            <li>
              <a href="#" className="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">About</a>
            </li>
            <li>
              <a href="#" className="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Services</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    </>
  )
}

export default Navbar